package stablemarriagefinal;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

 class StableMarriageGUI extends javax.swing.JFrame {
    public StableMarriageGUI() {
        initComponents();
    }

  //Lines 14-144 are pregenerated by the Java Swing Constructor
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        listText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pairsText = new javax.swing.JTextArea();
        menButton = new javax.swing.JButton();
        womenButton = new javax.swing.JButton();
        inputField = new javax.swing.JFormattedTextField();
        label2 = new java.awt.Label();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Lao MN", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 0, 255));
        label1.setText("MatchMaker");

        listText.setColumns(20);
        listText.setRows(5);
        listText.setDoubleBuffered(true);
        jScrollPane1.setViewportView(listText);

        pairsText.setColumns(20);
        pairsText.setRows(5);
        jScrollPane2.setViewportView(pairsText);

        menButton.setText("Men Propose ->");
        menButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menButtonMouseClicked(evt);
            }
        });

        womenButton.setText("Women Propose ->");
        womenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                womenButtonMousePressed(evt);
            }
        });

        inputField.setToolTipText("Which file would you like to use?");

        label2.setText("Which file would you like to use?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(menButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addGap(260, 260, 260))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(womenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menButton)
                            .addComponent(womenButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menButtonMouseClicked
        String tempString = "";
        tempString += "List of Men and Women, with their "
                + "preferences in order: \n";
        try {
            StableMarriageFinal.readFile(inputField.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StableMarriageGUI.class.
                    getName()).log(Level.SEVERE, null, ex);
        }
        for (StableMarriageFinal.Person p : StableMarriageFinal.listPeople){
            tempString += (p.toString() + "\n" );                               
        }
        listText.setText(tempString);
        StableMarriageFinal.arrangeMarriages("m");
        StableMarriageFinal.setPairList();
        
        pairsText.setText("Stable pairs when Men propose: \n" +
                StableMarriageFinal.p1 + "\n" +
                StableMarriageFinal.p2 + "\n" +
                StableMarriageFinal.p3 + "\n" +
                StableMarriageFinal.p4 + "\n" +
                StableMarriageFinal.p5);
        System.out.println("m");
    }//GEN-LAST:event_menButtonMouseClicked

    private void womenButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_womenButtonMousePressed
        String tempString = "";
        tempString += "List of Men and Women, with their "
                + "preferences in order: \n";
        try {
            StableMarriageFinal.readFile(inputField.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StableMarriageGUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        for (StableMarriageFinal.Person p : StableMarriageFinal.listPeople){
            tempString += (p.toString() + "\n" );                               
        }
        listText.setText(tempString);
        StableMarriageFinal.arrangeMarriages("f");
        StableMarriageFinal.setPairList();
        
        pairsText.setText("Stable pairs when Women propose: \n" +
                StableMarriageFinal.p1 + "\n" +
                StableMarriageFinal.p2 + "\n" +
                StableMarriageFinal.p3 + "\n" +
                StableMarriageFinal.p4 + "\n" +
                StableMarriageFinal.p5);
        System.out.println("f");
    }//GEN-LAST:event_womenButtonMousePressed

   //Lines 194-244 are pregenerated by Java Swing Constructor
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StableMarriageGUI.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StableMarriageGUI.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StableMarriageGUI.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StableMarriageGUI.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StableMarriageGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField inputField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextArea listText;
    private javax.swing.JButton menButton;
    public static javax.swing.JTextArea pairsText;
    private javax.swing.JButton womenButton;
    // End of variables declaration//GEN-END:variables
}
